/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ArrearsRouteImport } from './routes/arrears'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LandlordIndexRouteImport } from './routes/Landlord/index'
import { Route as TenantReceiptsRouteImport } from './routes/tenant/receipts'
import { Route as TenantMaintenanceRouteImport } from './routes/tenant/maintenance'
import { Route as TenantDocumentsRouteImport } from './routes/tenant/documents'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPropertiesRouteImport } from './routes/admin/properties'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminLandlordsRouteImport } from './routes/admin/landlords'
import { Route as AdminFeaturesRouteImport } from './routes/admin/features'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrearsRoute = ArrearsRouteImport.update({
  id: '/arrears',
  path: '/arrears',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordIndexRoute = LandlordIndexRouteImport.update({
  id: '/Landlord/',
  path: '/Landlord/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantReceiptsRoute = TenantReceiptsRouteImport.update({
  id: '/tenant/receipts',
  path: '/tenant/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMaintenanceRoute = TenantMaintenanceRouteImport.update({
  id: '/tenant/maintenance',
  path: '/tenant/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDocumentsRoute = TenantDocumentsRouteImport.update({
  id: '/tenant/documents',
  path: '/tenant/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandlordsRoute = AdminLandlordsRouteImport.update({
  id: '/admin/landlords',
  path: '/admin/landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/admin/features',
  path: '/admin/features',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrears': typeof ArrearsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/landlords': typeof AdminLandlordsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/receipts': typeof TenantReceiptsRoute
  '/Landlord/': typeof LandlordIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrears': typeof ArrearsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/landlords': typeof AdminLandlordsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/receipts': typeof TenantReceiptsRoute
  '/Landlord': typeof LandlordIndexRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrears': typeof ArrearsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/landlords': typeof AdminLandlordsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/receipts': typeof TenantReceiptsRoute
  '/Landlord/': typeof LandlordIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrears'
    | '/documents'
    | '/expenses'
    | '/forgot-password'
    | '/invoices'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/properties'
    | '/register'
    | '/settings'
    | '/tenants'
    | '/units'
    | '/admin/features'
    | '/admin/landlords'
    | '/admin/monitoring'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/tenant/documents'
    | '/tenant/maintenance'
    | '/tenant/receipts'
    | '/Landlord/'
    | '/admin/'
    | '/staff/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrears'
    | '/documents'
    | '/expenses'
    | '/forgot-password'
    | '/invoices'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/properties'
    | '/register'
    | '/settings'
    | '/tenants'
    | '/units'
    | '/admin/features'
    | '/admin/landlords'
    | '/admin/monitoring'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/tenant/documents'
    | '/tenant/maintenance'
    | '/tenant/receipts'
    | '/Landlord'
    | '/admin'
    | '/staff'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/arrears'
    | '/documents'
    | '/expenses'
    | '/forgot-password'
    | '/invoices'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/properties'
    | '/register'
    | '/settings'
    | '/tenants'
    | '/units'
    | '/admin/features'
    | '/admin/landlords'
    | '/admin/monitoring'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/tenant/documents'
    | '/tenant/maintenance'
    | '/tenant/receipts'
    | '/Landlord/'
    | '/admin/'
    | '/staff/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrearsRoute: typeof ArrearsRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpensesRoute: typeof ExpensesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PropertiesRoute: typeof PropertiesRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TenantsRoute: typeof TenantsRoute
  UnitsRoute: typeof UnitsRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminLandlordsRoute: typeof AdminLandlordsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  TenantDocumentsRoute: typeof TenantDocumentsRoute
  TenantMaintenanceRoute: typeof TenantMaintenanceRoute
  TenantReceiptsRoute: typeof TenantReceiptsRoute
  LandlordIndexRoute: typeof LandlordIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrears': {
      id: '/arrears'
      path: '/arrears'
      fullPath: '/arrears'
      preLoaderRoute: typeof ArrearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Landlord/': {
      id: '/Landlord/'
      path: '/Landlord'
      fullPath: '/Landlord/'
      preLoaderRoute: typeof LandlordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/receipts': {
      id: '/tenant/receipts'
      path: '/tenant/receipts'
      fullPath: '/tenant/receipts'
      preLoaderRoute: typeof TenantReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/maintenance': {
      id: '/tenant/maintenance'
      path: '/tenant/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof TenantMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/documents': {
      id: '/tenant/documents'
      path: '/tenant/documents'
      fullPath: '/tenant/documents'
      preLoaderRoute: typeof TenantDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landlords': {
      id: '/admin/landlords'
      path: '/admin/landlords'
      fullPath: '/admin/landlords'
      preLoaderRoute: typeof AdminLandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/admin/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrearsRoute: ArrearsRoute,
  DocumentsRoute: DocumentsRoute,
  ExpensesRoute: ExpensesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PropertiesRoute: PropertiesRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TenantsRoute: TenantsRoute,
  UnitsRoute: UnitsRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminLandlordsRoute: AdminLandlordsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  TenantDocumentsRoute: TenantDocumentsRoute,
  TenantMaintenanceRoute: TenantMaintenanceRoute,
  TenantReceiptsRoute: TenantReceiptsRoute,
  LandlordIndexRoute: LandlordIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  TenantIndexRoute: TenantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
